# Generated by Django 4.1.3 on 2022-12-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uslugi',
            table='uslugis',
        ),
    ]
