# Generated by Django 4.1.3 on 2022-12-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab2app', '0002_alter_uslugi_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerdicription', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=25)),
                ('datecreated', models.DateField(blank=True, null=True)),
                ('dateshipped', models.DateField(blank=True, null=True)),
                ('dateclosed', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facts',
                'managed': False,
            },
        ),
    ]
